/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminBook: typeof import('./components/rootCenter/adminBook.vue')['default']
    ApiBook: typeof import('./components/rootCenter/apiBook.vue')['default']
    Biao1: typeof import('./components/Board/biao1.vue')['default']
    Biao2: typeof import('./components/Board/biao2.vue')['default']
    Biao3: typeof import('./components/Board/biao3.vue')['default']
    Biao4: typeof import('./components/Board/biao4.vue')['default']
    Biao5: typeof import('./components/Board/biao5.vue')['default']
    Biao6: typeof import('./components/Board/biao6.vue')['default']
    Biao7: typeof import('./components/Board/biao7.vue')['default']
    'CRUD.appelAtion': typeof import('./components/Crud/CRUD.appelAtion.vue')['default']
    'CRUD.operation': typeof import('./components/Crud/CRUD.operation.vue')['default']
    DataBoard: typeof import('./components/dataBoard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    GeRen: typeof import('./components/geRen.vue')['default']
    LineEcharts1: typeof import('./components/echarts/lineEcharts1.vue')['default']
    LineEcharts2: typeof import('./components/echarts/lineEcharts2.vue')['default']
    LineEchartsL: typeof import('./components/echarts/lineEchartsL.vue')['default']
    Other: typeof import('./components/echarts/other.vue')['default']
    Pagination: typeof import('./components/Crud/Pagination.vue')['default']
    PaginationPrevNext: typeof import('./components/Crud/PaginationPrevNext.vue')['default']
    PieEcharts1: typeof import('./components/echarts/pieEcharts1.vue')['default']
    PieEcharts2: typeof import('./components/echarts/pieEcharts2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    'RR.operation': typeof import('./components/Crud/RR.operation.vue')['default']
    'UD.operation': typeof import('./components/Crud/UD.operation.vue')['default']
    'UD.operationAdmin': typeof import('./components/Crud/UD.operationAdmin.vue')['default']
    UserBook: typeof import('./components/rootCenter/userBook.vue')['default']
  }
}
